homeassistant:
  # name: Chateau Charlois
  # latitude: !secret homelocation_lat
  # longitude: !secret homelocation_long
  # elevation: 0
  # unit_system: metric
  # time_zone: Europe/Amsterdam
  customize_glob:
    sensor.*_verbruik_totaal:
      last_reset: '1970-01-01T00:00:00+00:00'
      device_class: energy
      state_class: measurement
    sensor.youless_*_meterstand:
      last_reset: '1970-01-01T00:00:00+00:00'
      device_class: energy
      state_class: measurement
  customize: !include customize.yaml

frontend:
  themes: !include_dir_merge_named themes

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - 172.17.0.0/24
    - ::1

system_health:

person:

config:

energy:

mobile_app:

logger:
  default: warning

recorder:
  db_url: !secret db_url
  purge_keep_days: 30

updater:
  include_used_components: true

media_source:

discovery:
  ignore:
    - axis
    - homekit
history:

logbook:

wake_on_lan:

stream:

fastdotcom:

sun:

hue:
  bridges:
    - host: !secret hue_bridge_ip
      allow_unreachable: true
      allow_hue_groups: false

apple_tv:
  - host: !secret woonkamer_atv_ip
    login_id: !secret woonkamer_atv_login_id
    name: Woonkamer Apple TV
    start_off: true
    credentials: !secret woonkamer_atv_credentials
  - host: !secret slaapkamer_atv_ip
    login_id: !secret slaapkamer_atv_login_id
    name: Slaapkamer Apple TV
    start_off: true
    credentials: !secret slaapkamer_atv_credentials

media_player:
  - platform: channels
    name: Woonkamer Live TV
    host: !secret woonkamer_atv_ip
  - platform: channels
    name: Slaapkamer Live TV
    host: !secret slaapkamer_atv_ip

map:

device_tracker:
  - platform: nmap_tracker
    hosts:
      - 192.168.1.46
      - 192.168.1.47
      - 192.168.1.48
      - 192.168.1.49
      - 192.168.1.50
    track_new_devices: true
    interval_seconds: 30
    consider_home: 600

proximity:
  home:
    devices:
      - device_tracker.iphone_van_deborah
      - device_tracker.iphone_van_martien
    tolerance: 50
    unit_of_measurement: km

  # - platform: bluetooth_tracker
  #   track_new_devices: false
  #   interval_seconds: 30
  #   consider_home: 600

alarm_control_panel:
  - platform: manual
    name: Alarm
    code: !secret alarm_panel_code
    delay_time: 0
    arming_time: 0


# Text to speech
tts:
  - platform: google_translate
    service_name: google_say
    cache: true
    language: nl

netatmo:
  client_id: !secret netatmo_client_id
  client_secret: !secret netatmo_client_secret

climate:
  - platform: generic_thermostat
    name: Gang
    heater: input_boolean.gangkachel
    target_sensor: sensor.gang_temperature
    min_temp: 7
    max_temp: 21
    cold_tolerance: 0.5
    hot_tolerance: 0.5
    min_cycle_duration:
      minutes: 15
    away_temp: 7
    target_temp: 7

plant:
  grote_woonkamer_plant:
    sensors:
      moisture: sensor.grote_woonkamer_plant_moisture
      battery: sensor.grote_woonkamer_plant_battery
      temperature: sensor.grote_woonkamer_plant_temperature
      conductivity: sensor.grote_woonkamer_plant_conductivity
      brightness: sensor.grote_woonkamer_plant_brightness
    min_moisture: 20
    min_conductivity: 100

nzbget:
  host: !secret nzbget_host
  username: !secret nzbget_user
  password: !secret nzbget_password

timer:
  hek_lock:
    name: Hek Lock Timer
    icon: mdi:timer
  deurbel_ingedrukt:
    name: Deurbel Ingedrukt Timer

lock:
  - platform: template
    name: Hek
    value_template: "{{ not is_state('timer.hek_lock', 'active') }}"
    lock:
    unlock:
      - service: dahua_vto.open_door
        data_template:
          entity_id: sensor.deurbel
          channel: 1
          short_number: HA

calendar:
  - platform: caldav
    username: !secret caldav_user
    password: !secret caldav_password
    url: !secret caldav_url

landroid_cloud:
  - email: !secret landroid_email
    password: !secret landroid_password

notify:
  - name: Pushover
    platform: pushover
    api_key: !secret pushover_api_key
    user_key: !secret pushover_user_key
  - name: NotifyAll
    platform: group
    services:
      - service: mobile_app_iphone_van_martien
      - service: mobile_app_martiens_ipad_pro
      - service: mobile_app_macbook_pro_van_martien
      - service: mobile_app_iphone_van_deborah
  - name: martien
    platform: group
    services:
      - service: mobile_app_iphone_van_martien
      - service: mobile_app_martiens_ipad_pro
      - service: mobile_app_macbook_pro_van_martien

input_datetime:
  besproeiingstarttijd:
    name: Besproeiing Starttijd
    has_date: false
    has_time: true

input_text:
  card_containers:
    initial: Containers
  software_version:
    initial: Version

lovelace:
  mode: storage
 
ios: !include includes/ios.yaml
google_assistant: !include includes/google_assistant.yaml
homekit: !include includes/homekit.yaml
light: !include includes/light.yaml
zone: !include includes/zones.yaml
switch: !include includes/switch.yaml
input_boolean: !include includes/input_boolean.yaml
input_select: !include includes/input_select.yaml
input_number: !include includes/input_number.yaml
binary_sensor: !include includes/binary_sensor.yaml
sensor: !include includes/sensor.yaml
utility_meter: !include includes/utility_meter.yaml
counter: !include includes/counters.yaml
group: !include includes/groups.yaml
automation: !include_dir_merge_list automations/
scene: !include_dir_merge_list scenes/
shell_command: !include includes/shell_commands.yaml
script: !include_dir_merge_named scripts/