homeassistant:
  name: Chateau Charlois
  latitude: !secret homelocation_lat
  longitude: !secret homelocation_long
  elevation: 0
  unit_system: metric
  time_zone: Europe/Amsterdam
  customize: !include customize.yaml

system_health:

person:

hacs:
  token: !secret hacs_token

breaking_changes:

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes

# Enables configuration UI
config:

mobile_app:

logger:
  default: warning

recorder:
  db_url: !secret db_url
  purge_keep_days: 7
  purge_interval: 1

http:
  ip_ban_enabled: false
  login_attempts_threshold: 50
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  base_url: !secret ha_baseurl

updater:
  include_used_components: true

lovelace:
  mode: yaml

browser_mod:

discovery:
  ignore:
    - axis
    - homekit
history:

logbook:

wake_on_lan:

stream:

fastdotcom:

sun:

rfxtrx:
   device: /dev/serial/by-id/usb-RFXCOM_RFXtrx433_A1YI1ZVU-if00-port0
   debug: False

homekit:
  auto_start: False
  filter:
    include_domains:
      - alarm_control_panel
    include_entities:
      - climate.gang
      - climate.tesla_model_3_hvac_climate_system
      - climate.gang_vloerverwarming
      - climate.badkamer_vloerverwarming
      - climate.veranda_kachel
      - sensor.slaapkamer_temperature
      - sensor.keuken_temperature
      - sensor.babykamer_temperature
      - sensor.buiten_temperature
      - binary_sensor.woonkamer_motion
      - binary_sensor.tv_kamer_motion
      - binary_sensor.keuken_motion
      - binary_sensor.gang_motion
      - binary_sensor.overloop_motion
      - binary_sensor.keukendeur
      - binary_sensor.badkamerraam
      - binary_sensor.washok_raam
      - binary_sensor.slaapkamer_raam
      - binary_sensor.charlies_slaapkamer_raam
      - binary_sensor.grote_slaapkamer_raam
      - binary_sensor.kleine_slaapkamer_raam
      - binary_sensor.overloop_raam
      - binary_sensor.wc_boven
      - binary_sensor.woonkamer_raam_1
      - binary_sensor.woonkamer_raam_2
      - binary_sensor.woonkamer_raam_3
      - script.badkamer_licht_therapie
      - script.charlies_kamer_loop
      - switch.kaku_switch_1
      - switch.kaku_switch_2
      - switch.kaku_switch_3
      - switch.kerstverlichting_buiten
      - switch.keukenkachel
      - switch.wasmachine_sonoff
      - switch.badkamerfan_sonoff
      - switch.gangkachel_sonoff
      - switch.droger_sonoff
      - switch.looppoort_deurbel_relay_1
      - switch.ganglicht
      - switch.veranda_kachel
      - switch.veranda_verlichting
      - input_boolean.homemode_home
      - input_boolean.homemode_away
      - input_boolean.homemode_night
      - input_boolean.homemode_vacation
      - input_boolean.homemode_bedtime
      - input_boolean.homemode_guest
      - input_boolean.scene_goodmorning
      - input_boolean.scene_jarvis
      - input_boolean.scene_sfeer
      - input_boolean.scene_helder
      - input_boolean.scene_bedtime
      - input_boolean.gangkachel_schema
      - input_boolean.keukenkachel_schema
      - lock.tesla_model_3_charger_door_lock
      - lock.tesla_model_3_door_lock
  entity_config:
    alarm_control_panel.alarm:
      code: !secret alarm_panel_code

hue:
  bridges:
    - host: !secret hue_bridge_ip
      allow_unreachable: true
      allow_hue_groups: false

tuya:
  username: !secret tuya_username
  password: !secret tuya_password
  country_code: 31
  platform: smart_life

apple_tv:
  - host: !secret woonkamer_atv_ip
    login_id: !secret woonkamer_atv_login_id
    name: Woonkamer Apple TV
    start_off: true
    credentials: !secret woonkamer_atv_credentials
  - host: !secret slaapkamer_atv_ip
    login_id: !secret slaapkamer_atv_login_id
    name: Slaapkamer Apple TV
    start_off: true
    credentials: !secret slaapkamer_atv_credentials

remote:
  - platform: harmony
    name: Woonkamer
    host: !secret harmony_ip

transmission:
  host: !secret transmission_ip
  username: !secret transmission_username
  password: !secret transmission_password

sabnzbd:
  api_key: !secret sabz_api_key
  host: !secret sabz_ip
  path: /sabnzbd
  name: sab
  port: 8080
  ssl: false
  sensors:
    - current_status
    - speed
    - queue_size
    - queue_remaining
    - disk_size
    - disk_free
    - queue_count
    - day_size
    - week_size
    - month_size
    - total_size

media_player:
  - platform: channels
    name: Woonkamer Live TV
    host: !secret woonkamer_atv_ip
  - platform: channels
    name: Slaapkamer Live TV
    host: !secret slaapkamer_atv_ip

ios:
  push:
    categories:
      - name: deurbel
        identifier: 'camera'
        actions:
          - identifier: 'OPEN_HEK'
            title: 'Hek Openen'
            activationMode: 'background'
            authenticationRequired: true
            destructive: true
      - name: alarmgaataf
        identifier: 'alarm_gaat_af'
        actions:
          - identifier: 'ALARM_DISARM'
            title: 'Alarm Uitschakelen'
            activationMode: 'background'
            authenticationRequired: true
            destructive: true
      - name: bewegingniemandthuis
        identifier: 'beweging_niemand_thuis'
        actions:
          - identifier: 'ALARM_SOS'
            title: 'Alarm SOS!'
            activationMode: 'background'
            authenticationRequired: true
            destructive: true
      - name: verlichtingnogaan
        identifier: 'verlichting_nog_aan'
        actions:
          - identifier: 'ALLE_LICHTEN_UIT'
            title: 'Uitschakelen'
            activationMode: 'background'
            authenticationRequired: true
            destructive: true

map:

weather:
  - platform: buienradar
    name: 'Rotterdam'
    latitude: !secret homelocation_lat
    longitude: !secret homelocation_long
    forecast: True

device_tracker:
  - platform: nmap_tracker
    hosts:
      - 192.168.1.46
      - 192.168.1.47
      - 192.168.1.48
      - 192.168.1.49
      - 192.168.1.50
    track_new_devices: true
    interval_seconds: 30
    consider_home: 600

  - platform: bluetooth_tracker
    track_new_devices: false
    interval_seconds: 30
    consider_home: 600

alarm_control_panel:
  - platform: manual
    name: Alarm
    code: !secret alarm_panel_code
    pending_time: 5
    delay_time: 0
    trigger_time: 4
    disarmed:
      trigger_time: 0
    armed_home:
      pending_time: 5
      delay_time: 0

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say
    cache: true
    language: nl

netatmo:
  client_id: !secret netatmo_client_id
  client_secret: !secret netatmo_client_secret

climate:
  - platform: generic_thermostat
    name: Gang
    heater: input_boolean.gangkachel
    target_sensor: sensor.gang_temperature
    min_temp: 7
    max_temp: 21
    cold_tolerance: 0.5
    hot_tolerance: 0.5
    away_temp: 7
    target_temp: 7

doorbird:
  devices:
    - host: !secret doorbird_ip
      username: !secret doorbird_username
      password: !secret doorbird_password
      name: Looppoort Deurbel
      token: !secret doorbird_token

camera:
  - platform: foscam
    name: Babykamer
    ip: !secret babykamercam_ip
    username: !secret foscam_username
    password: !secret foscam_password
  - platform: foscam
    name: Oprit
    ip: !secret opritcam_ip
    username: !secret foscam_username
    password: !secret foscam_password
  - platform: doorbird
  - platform: generic
    name: Veranda
    still_image_url: !secret verandacam_still_image_url
    stream_source: !secret verandacam_stream_source

utility_meter:
  daily_youless_zonnepanelen:
    source: sensor.youless_zonnepanelen_meterstand
    cycle: daily
  weekly_youless_zonnepanelen:
    source: sensor.youless_zonnepanelen_meterstand
    cycle: weekly
  monthly_youless_zonnepanelen:
    source: sensor.youless_zonnepanelen_meterstand
    cycle: monthly
  yearly_youless_zonnepanelen:
    source: sensor.youless_zonnepanelen_meterstand
    cycle: yearly

  daily_youless_wall_charger:
    source: sensor.youless_wall_charger_meterstand
    cycle: daily
  weekly_youless_wall_charger:
    source: sensor.youless_wall_charger_meterstand
    cycle: weekly
  monthly_youless_wall_charger:
    source: sensor.youless_wall_charger_meterstand
    cycle: monthly
  yearly_youless_wall_charger:
    source: sensor.youless_wall_charger_meterstand
    cycle: yearly

notify:
  - name: Pushover
    platform: pushover
    api_key: !secret pushover_api_key
    user_key: !secret pushover_user_key
  - name: NotifyAll
    platform: group
    services:
      - service: mobile_app_martiens_iphone_11_pro

tesla:
  username: !secret tesla_username
  password: !secret tesla_password
  scan_interval: 900

light: !include light.yaml
zone: !include zones.yaml
switch: !include switch.yaml
input_boolean: !include input_boolean.yaml
input_select: !include input_select.yaml
binary_sensor: !include binary_sensor.yaml
sensor: !include sensor.yaml
automation: !include_dir_merge_list automations/
script: !include_dir_merge_named scripts/
group: !include groups.yaml
