homeassistant:
  # name: Chateau Charlois
  # latitude: !secret homelocation_lat
  # longitude: !secret homelocation_long
  # elevation: 0
  # unit_system: metric
  # time_zone: Europe/Amsterdam
  customize: !include customize.yaml

frontend:
  themes: !include_dir_merge_named themes

system_health:

person:

# hacs:
#   token: !secret hacs_token

config:

mobile_app:

# mqtt:
#   broker: !secret mqtt_broker
#   username: !secret mqtt_username
#   password: !secret mqtt_password

logger:
  default: warning

recorder:
#  db_url: !secret db_url
  purge_keep_days: 7
  # purge_interval: 1

# http:
#   ip_ban_enabled: false
#   login_attempts_threshold: 50
#   ssl_certificate: /ssl/fullchain.pem
#   ssl_key: /ssl/privkey.pem
#   base_url: !secret ha_baseurl

updater:
  include_used_components: true

browser_mod:

discovery:
  ignore:
    - axis
    - homekit
history:

logbook:

wake_on_lan:

stream:

fastdotcom:

sun:

# rfxtrx:
#    device: /dev/serial/by-id/usb-RFXCOM_RFXtrx433_A1YI1ZVU-if00-port0
#    debug: False

# homekit:
#   auto_start: False
#   filter:
#     include_domains:
#       - alarm_control_panel
#     include_entities:
#       - climate.gang
#       - climate.tesla_model_3_hvac_climate_system
#       - climate.gang_vloerverwarming
#       - climate.badkamer_vloerverwarming
#       - climate.veranda_kachel
#       - sensor.slaapkamer_temperature
#       - sensor.keuken_temperature
#       - sensor.babykamer_temperature
#       - sensor.buiten_temperature
#       - binary_sensor.woonkamer_motion
#       - binary_sensor.tv_kamer_motion
#       - binary_sensor.keuken_motion
#       - binary_sensor.gang_motion
#       - binary_sensor.overloop_motion
#       - binary_sensor.keukendeur
#       - binary_sensor.badkamerraam
#       - binary_sensor.washok_raam
#       - binary_sensor.slaapkamer_raam
#       - binary_sensor.charlies_slaapkamer_raam
#       - binary_sensor.grote_slaapkamer_raam
#       - binary_sensor.kleine_slaapkamer_raam
#       - binary_sensor.overloop_raam
#       - binary_sensor.wc_boven
#       - binary_sensor.woonkamer_raam_1
#       - binary_sensor.woonkamer_raam_2
#       - binary_sensor.woonkamer_raam_3
#       - script.badkamer_licht_therapie
#       - script.charlies_kamer_loop
#       - switch.kaku_switch_1
#       - switch.kaku_switch_2
#       - switch.kaku_switch_3
#       - switch.kerstverlichting_buiten
#       - switch.keukenkachel
#       - switch.wasmachine_sonoff
#       - switch.badkamerfan_sonoff
#       - switch.gangkachel_sonoff
#       - switch.droger_sonoff
#       - switch.looppoort_deurbel_relay_1
#       - switch.ganglicht
#       - switch.veranda_kachel
#       - switch.veranda_verlichting
#       - input_boolean.homemode_home
#       - input_boolean.homemode_away
#       - input_boolean.homemode_night
#       - input_boolean.homemode_vacation
#       - input_boolean.homemode_bedtime
#       - input_boolean.homemode_guest
#       - input_boolean.scene_goodmorning
#       - input_boolean.scene_jarvis
#       - input_boolean.scene_sfeer
#       - input_boolean.scene_helder
#       - input_boolean.scene_bedtime
#       - input_boolean.gangkachel_schema
#       - input_boolean.keukenkachel_schema
#       - lock.tesla_model_3_charger_door_lock
#       - lock.tesla_model_3_door_lock
  # entity_config:
  #   alarm_control_panel.alarm:
  #     code: !secret alarm_panel_code

hue:
  bridges:
    - host: !secret hue_bridge_ip
      allow_unreachable: true
      allow_hue_groups: false

apple_tv:
  - host: !secret woonkamer_atv_ip
    login_id: !secret woonkamer_atv_login_id
    name: Woonkamer Apple TV
    start_off: true
    credentials: !secret woonkamer_atv_credentials
  - host: !secret slaapkamer_atv_ip
    login_id: !secret slaapkamer_atv_login_id
    name: Slaapkamer Apple TV
    start_off: true
    credentials: !secret slaapkamer_atv_credentials

# remote:
#   - platform: harmony
#     name: Woonkamer
#     host: !secret harmony_ip

media_player:
  - platform: channels
    name: Woonkamer Live TV
    host: !secret woonkamer_atv_ip
  - platform: channels
    name: Slaapkamer Live TV
    host: !secret slaapkamer_atv_ip

spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

map:

weather:
  - platform: buienradar
    name: 'Rotterdam'
    latitude: !secret homelocation_lat
    longitude: !secret homelocation_long
    forecast: True

device_tracker:
  - platform: nmap_tracker
    hosts:
      - 192.168.1.46
      - 192.168.1.47
      - 192.168.1.48
      - 192.168.1.49
      - 192.168.1.50
    track_new_devices: true
    interval_seconds: 30
    consider_home: 600

proximity:
  home:
    devices:
      - device_tracker.iphone_van_deborah
      - device_tracker.iphone_van_martien
    tolerance: 50
    unit_of_measurement: km

  # - platform: bluetooth_tracker
  #   track_new_devices: false
  #   interval_seconds: 30
  #   consider_home: 600

zoneminder:
  - host: !secret zoneminder_host
    username: !secret zoneminder_username
    password: !secret zoneminder_password
    ssl: true
    verify_ssl: false

alarm_control_panel:
  - platform: manual
    name: Alarm
    code: !secret alarm_panel_code
    delay_time: 0
    arming_time: 0


# Text to speech
tts:
  - platform: google_translate
    service_name: google_say
    cache: true
    language: nl

netatmo:
  client_id: !secret netatmo_client_id
  client_secret: !secret netatmo_client_secret

climate:
  - platform: generic_thermostat
    name: Gang
    heater: input_boolean.gangkachel
    target_sensor: sensor.gang_temperature
    min_temp: 7
    max_temp: 21
    cold_tolerance: 0.5
    hot_tolerance: 0.5
    min_cycle_duration:
      minutes: 15
    away_temp: 7
    target_temp: 7

plant:
  grote_woonkamer_plant:
    sensors:
      moisture: sensor.mi_flora_moisture
      battery: sensor.mi_flora_battery
      temperature: sensor.mi_flora_temperature
      conductivity: sensor.mi_flora_conductivity
      brightness: sensor.mi_flora_light_intensity
    min_moisture: 20
    min_conductivity: 100

nzbget:
  host: !secret nzbget_host
  username: !secret nzbget_user
  password: !secret nzbget_password

# doorbird:
#   devices:
#     - host: !secret doorbird_ip
#       username: !secret doorbird_username
#       password: !secret doorbird_password
#       name: Deurbel
#       token: !secret doorbird_token
#       events:
#         - somebody_pressed_the_button
#         - relay_unlocked

camera:
  - platform: zoneminder
  - platform: buienradar

lock:
  - platform: template
    name: Inrijpoort
    value_template: "{{ is_state('switch.deurbel_relay_1', 'off') }}"
    lock:
      service: switch.turn_on
      data:
        entity_id: switch.deurbel_relay_1
    unlock:
      service: switch.turn_on
      data:
        entity_id: switch.deurbel_relay_1

calendar:
  - platform: caldav
    username: !secret caldav_user
    password: !secret caldav_password
    url: !secret caldav_url

landroid_cloud:
  - email: !secret landroid_email
    password: !secret landroid_password

notify:
  - name: Pushover
    platform: pushover
    api_key: !secret pushover_api_key
    user_key: !secret pushover_user_key
  - name: NotifyAll
    platform: group
    services:
      - service: mobile_app_iphone_van_martien
      - service: mobile_app_martiens_ipad_pro
      - service: mobile_app_iphone_van_deborah
  - name: martien
    platform: group
    services:
      - service: mobile_app_iphone_van_martien
      - service: mobile_app_martiens_ipad_pro

tesla:
  username: !secret tesla_username
  password: !secret tesla_password
  scan_interval: 900

input_datetime:
  besproeiingstarttijd:
    name: Besproeiing Starttijd
    has_date: false
    has_time: true

input_text:
  card_containers:
    initial: Containers
  software_version:
    initial: Version

panel_iframe: !include includes/panel_iframe.yaml    
ios: !include includes/ios.yaml
google_assistant: !include includes/google_assistant.yaml
light: !include includes/light.yaml
zone: !include includes/zones.yaml
switch: !include includes/switch.yaml
input_boolean: !include includes/input_boolean.yaml
input_select: !include includes/input_select.yaml
input_number: !include includes/input_number.yaml
binary_sensor: !include includes/binary_sensor.yaml
sensor: !include includes/sensor.yaml
group: !include includes/groups.yaml
automation: !include_dir_merge_list automations/
scene: !include_dir_merge_list scenes/
script: !include_dir_merge_named scripts/