##########################################################################
#                                                                        #
#                              * SETTINGS *                              #
#                                                                        #
##########################################################################

anchors:
  ⚓₁: &title
    entity: sensor.placeholder
    tap_action:
      action: none
    hold_action:
      action: none
    type: state-label
  ⚓₂: &title-style
    color: '#bcbebf'
    font-family: SF Text
    font-size: 2.4vw
    font-weight: 500
    max-width: 1px
    cursor: default
##########################################################################
#                                                                        #
#                              * LOVELACE *                              #
#                                                                        #
##########################################################################

title: Home
views:
  - panel: true
    path: default_view
    cards:
      - type: picture-elements
        image: /local/tablet/background.png
        elements:

          # markdown fix
          - type: custom:hui-element
            card_type: markdown
            style: {opacity: 0}
            content: preload
          ##########################################################################
          #                                                                        #
          #                              * SIDEBAR *                               #
          #                                                                        #
          ##########################################################################

          - type: image
            image: /local/tablet/sidebar.png
            style:
              {top: 49.24%, left: 10.6%, width: 21.5%, pointer-events: none, border-right: '1.5px solid rgba(58,69,73,0.2)'}

          #################################################
          #                                               #
          #                   MARKDOWN                    #
          #                                               #
          #################################################
          - type: 'custom:hui-markdown-card'
            class: sidebar
            style:
              top: 9%
              left: 11.1%
            content: >
              <span>{{ now().strftime('%H') }}<span>:</span>{{now().strftime('%M') }}</span> 
              
              
              <font color='#6a7377'><b>{{states('sensor.sidebar_day') }}</b><br> 
              <b>{{states('sensor.sidebar_date') }}</b> </font><br>  


              <b>{{states('sensor.sidebar_greeting') }}</b> 
              
              
              <b>{{states('sensor.sidebar_active') }}</b> 

              
              <font color='#6a7377'> 
              {{states('sensor.sidebar_weather') }}


              {% if is_state('switch.werk_laptop', 'on') %}
              {{'\u26A0\uFE0F'}} Laptop staat aan. {% endif %}
              
              {% if is_state('binary_sensor.dsmr_availability', 'off') %}
              {{'\u26A0\uFE0F'}} DSMR is uitgeschakeld..{% endif %}

              {% if is_state('binary_sensor.plex_availability', 'off') %}
              {{'\u26A0\uFE0F'}} Plex is uitgeschakeld..{% endif %}
              </font>

