- title: Internet Security
  path: inetsecurity
  icon: mdi:shield-account
  cards:
    - type: custom:homekit-card
      home: false
      statePositionTop: true
      entities:
        - title: AdGuard Internet Filter
          entities:
            - entity: switch.adguard_filtering
            - entity: switch.adguard_protection
            - entity: switch.adguard_parental_control
            - entity: switch.adguard_query_log
            - entity: switch.adguard_safe_browsing
            - entity: switch.adguard_safe_search
        - title: AdGuard Statistieken
          entities:
            - entity: sensor.adguard_average_processing_speed
            - entity: sensor.adguard_dns_queries
            - entity: sensor.adguard_dns_queries_blocked
            - entity: sensor.adguard_dns_queries_blocked_ratio
            - entity: sensor.adguard_parental_control_blocked
            - entity: sensor.adguard_safe_browsing_blocked
            - entity: sensor.adguard_rules_count