# https://dwainscheeren.github.io/lovelace-dwains-theme/configuration/cameras.html

cameras:
  - entity: camera.oprit
  - entity: camera.deurbel
  - entity: camera.veranda
  - entity: camera.charliecam
  - entity: camera.muizencam