# https://dwainscheeren.github.io/lovelace-dwains-theme/configuration/house_information.html

house_information:
  favorites:
    - entity: input_boolean.homemode_home
    - entity: input_boolean.homemode_away
    - entity: input_boolean.scene_bedtime
    - entity: input_boolean.homemode_night

  addons:
    - name: Calendar
      icon: mdi:calendar
      path: 'dwains-theme/addons/house_information/calendar/page.yaml'
      data:
        calendars:
          - calendar.gezamenlijke_agenda
          - calendar.martien_s_agenda
          - calendar.deborah_s_agenda
          - calendar.onderhoud
