# https://dwainscheeren.github.io/lovelace-dwains-theme/configuration/more_page.html

# more_page:
#   addons:
#     - name: Hello more page
#       icon: fas:chart-area
#       path: 'dwains-theme/addons/more_page/hello-more-page/page.yaml'
#       data:
#         some_data: 'This is some data parsed.'
#         some_other_data: 'and some other data.'
more_page:
  addons:
    - name: Energie
      icon: mdi:transmission-tower
      path: 'dwains-theme/addons/more_page/power_usage/power_usage.yaml'
    - name: Tesla
      icon: mdi:car-electric
      path: 'dwains-theme/addons/more_page/tesla/tesla.yaml'
    - name: Afvalwijzer
      icon: mdi:recycle
      path: 'dwains-theme/addons/more_page/afvalwijzer/page.yaml'
      data:
        afval_vandaag: sensor.trash_today
        afval_morgen: sensor.trash_tomorrow
        afval_rest: sensor.trash_restafval
        afval_gft: sensor.trash_gft
        afval_papier: sensor.trash_papier
    - name: P2000
      icon: mdi:ambulance
      path: 'dwains-theme/addons/more_page/p2000/page.yaml'
    - name: Downloads
      icon: mdi:cloud-download
      path: 'dwains-theme/addons/more_page/downloads/downloads.yaml'
    - name: Home Assistant
      icon: mdi:home-assistant
      path: 'dwains-theme/addons/more_page/ha_view/ha_monitoring.yaml'
    - name: Netwerk
      icon: mdi:lan
      path: 'dwains-theme/addons/more_page/ubiquiti/unifi.yaml'
    - name: AdGuard
      icon: mdi:account-child-circle
      path: 'dwains-theme/addons/more_page/adguard/page.yaml'
    - name: Unraid
      icon: mdi:server
      path: 'dwains-theme/addons/more_page/unraid_monitoring/unraid_monitoring.yaml'