# https://dwainscheeren.github.io/lovelace-dwains-theme/configuration/persons.html

persons: 
  - name: Martien
    track: person.martien
    picture_path: 'images/Martien.png'
    page_entities:
      entities:
        - entity: sensor.martiens_iphone_11_pro_geocoded_location
        - entity: sensor.martiens_iphone_11_pro_activity
        - entity: sensor.martiens_iphone_11_pro_steps
        - entity: sensor.martiens_iphone_11_pro_distance
        - entity: sensor.martiens_iphone_11_pro_average_active_pace
        - entity: sensor.martiens_iphone_11_pro_battery_level
        - entity: sensor.martiens_iphone_11_pro_battery_state
  - name: Deborah
    track: person.deborah
    picture_path: 'images/Deborah.png'