# https://dwainscheeren.github.io/lovelace-dwains-theme/configuration/rooms.html

rooms:
  - name: Woonkamer
    icon: mdi:sofa
    light: group.woonkamer_verlichting
#    temperature: climate.netatmo_woonkamer
    climate: climate.netatmo_woonkamer
    motion: group.woonkamer_motion
    window: group.woonkamer_ramen
    plant: plant.grote_woonkamer_plant
    media_player: group.woonkamer_media_players
    more_entities:
      columns: 2 #optional
      entities:
        - entity: switch.tv_meubel_tuya
    addons:
      - name: Sonos
        icon: mdi:speaker
        path: 'dwains-theme/addons/rooms/woonkamer/sonos/page.yaml'
        button_path: 'dwains-theme/addons/rooms/woonkamer/sonos/button.yaml'
        data:
          entity: media_player.tvkamer
      - name: Live TV
        icon: mdi:tv-retro
        path: 'dwains-theme/addons/rooms/woonkamer/tv/page.yaml'
        button_path: 'dwains-theme/addons/rooms/woonkamer/tv/button.yaml'
        data:
          entity: media_player.woonkamer_live_tv
      - name: Grote Plant
        icon: mdi:leaf
        path: 'dwains-theme/addons/rooms/woonkamer/plant/page.yaml'
        button_path: 'dwains-theme/addons/rooms/woonkamer/plant/button.yaml'
        data:
          plant: plant.grote_woonkamer_plant
          plant_species: draceana arborea

  - name: Keuken
    icon: mdi:fridge-outline
    light: group.keuken_verlichting
    climate: climate.netatmo_keuken
    motion: binary_sensor.keuken_motion
    door: binary_sensor.keukendeur
    media_player: media_player.keuken
    page_entities:
      columns: 2
      entities:
        - entity: binary_sensor.lekkage_gootsteenkastje
    addons:
      - name: Sonos
        icon: mdi:speaker
        path: 'dwains-theme/addons/rooms/keuken/sonos/page.yaml'
        button_path: 'dwains-theme/addons/rooms/keuken/sonos/button.yaml'
        data:
          entity: media_player.keuken

  - name: Kantoor
    icon: mdi:desk
    light: group.kantoor_verlichting
    addons:
      - name: Printer
        icon: mdi:printer
        path: 'dwains-theme/addons/rooms/kantoor/printer/page.yaml'
        button_path: 'dwains-theme/addons/rooms/kantoor/printer/button.yaml'
        data:
          entity: sensor.hp_color_laserjet_pro_m478f_9f
      - name: Sonos
        icon: mdi:speaker
        path: 'dwains-theme/addons/rooms/kantoor/sonos/page.yaml'
        button_path: 'dwains-theme/addons/rooms/kantoor/sonos/button.yaml'
        data:
          entity: media_player.kantoor

  - name: Badkamer
    icon: mdi:shower
    light: group.badkamer_spots
    device: switch.badkamerfan_sonoff
    climate: climate.netatmo_badkamer
    media_player: media_player.badkamer
    window: binary_sensor.badkamerraam
    page_entities:
      columns: 2
      entities:
        - entity: binary_sensor.lekkage_badkamer
    addons:
      - name: Sonos
        icon: mdi:speaker
        path: 'dwains-theme/addons/rooms/badkamer/sonos/page.yaml'
        button_path: 'dwains-theme/addons/rooms/badkamer/sonos/button.yaml'
        data:
          entity: media_player.badkamer

  - name: Gang
    icon: mdi:shoe-print
    light: switch.ganglicht
    # temperature: sensor.gang_temperature
    climate: climate.gang
    motion: binary_sensor.gang_motion
#    door: binary_sensor.gangdeur
    more_entities:
      columns: 2 #optional
      entities:
        - entity: input_boolean.gangkachel_schema
        - entity: sensor.gangkachel_status
        - entity: switch.gangkachel_aanuit
        - entity: switch.gangkachel_highlow
        - entity: switch.gangkachel_sonoff
    page_entities:
      columns: 1 #optional
      show_title: 'false' #optional
      entities:
        - entity: sensor.gangkachel_status

  - name: Washok
    icon: mdi:washing-machine
    device: group.washok_apparaten
    page_entities:
      columns: 2 #optional
      show_title: 'false' #optional
      entities:
        - entity: sensor.wasmachine_huidig_verbruik
        - entity: sensor.wasmachine_verbruik_vandaag
        - entity: sensor.wasmachine_verbruik_gister
        - entity: sensor.wasmachine_verbruik_totaal
    more_entities:
      columns: 2 #optional
      entities:
        - entity: switch.wasmachine_sonoff
        - entity: switch.droger_sonoff

  - name: Slaapkamer
    icon: mdi:bed-king
    light: group.slaapkamer_spots
    # temperature: sensor.slaapkamer_temperature
    climate: climate.netatmo_slaapkamer
    window: group.slaapkamer_ramen

  - name: Charlie's Kamer
    icon: mdi:baby-face-outline
    light: light.babykamer
    # temperature: sensor.babykamer_temperature
    climate: climate.netatmo_charlie_s_kamer
    window: binary_sensor.charlies_slaapkamer_raam
    addons:
      - name: CharlieCam
        path: 'dwains-theme/addons/rooms/charlies-kamer/camera/page.yaml'
        button_path: 'dwains-theme/addons/rooms/charlies-kamer/camera/button.yaml'
        data:
          entity: camera.charliecam

  - name: Overloop
    icon: mdi:stairs
    light: group.overloop_spots
    motion: binary_sensor.overloop_motion
    device: binary_sensor.rookmelder_overloop
    window: binary_sensor.overloop_raam

  - name: WC Boven
    icon: mdi:paper-roll-outline
    light: group.wc_boven_spots
    window: binary_sensor.wc_boven
    page_entities:
      columns: 2
      entities:
        - entity: binary_sensor.lekkage_wc_boven

  - name: Kelder
    icon: mdi:rodent
    light: switch.kelderlicht
    page_entities:
      columns: 2 #optional
      show_title: 'false' #optional
      entities:
        - entity: binary_sensor.hoogwater_kelder
    addons:
      - name: Camera
        path: 'dwains-theme/addons/rooms/kelder/camera/page.yaml'
        button_path: 'dwains-theme/addons/rooms/kelder/camera/button.yaml'
        data:
          entity: camera.muizencam

  - name: Veranda & Achtertuin
    icon: mdi:pine-tree
    addons:
      - name: Sonos
        icon: mdi:speaker
        path: 'dwains-theme/addons/rooms/veranda/sonos/page.yaml'
        button_path: 'dwains-theme/addons/rooms/veranda/sonos/button.yaml'
        data:
          entity: media_player.veranda
      - name: Grasmaaier
        icon: mdi:robot-mower-outline
        path: 'dwains-theme/addons/rooms/veranda/grasmaaier/page.yaml'
        button_path: 'dwains-theme/addons/rooms/veranda/grasmaaier/button.yaml'
      - name: Besproeiing
        icon: mdi:sprinkler
        path: 'dwains-theme/addons/rooms/veranda/besproeiing/page.yaml'
        button_path: 'dwains-theme/addons/rooms/veranda/besproeiing/button.yaml'
      - name: Camera
        path: 'dwains-theme/addons/rooms/veranda/camera/page.yaml'
        button_path: 'dwains-theme/addons/rooms/veranda/camera/button.yaml'
        data:
          entity: camera.veranda

  - name: Oprit & Voortuin
    icon: mdi:gate
    lock: lock.inrijpoort
    addons:
      - name: Deurbel
        path: 'dwains-theme/addons/rooms/voortuin/camera/page.yaml'
        button_path: 'dwains-theme/addons/rooms/voortuin/camera/button.yaml'
        data:
          entity: camera.deurbel
      - name: Oprit
        path: 'dwains-theme/addons/rooms/oprit/camera/page.yaml'
        button_path: 'dwains-theme/addons/rooms/oprit/camera/button.yaml'
        data:
          entity: camera.oprit

  - name: Tesla
    icon: mdi:car-electric
    lock: group.tesla_sloten
    device: group.tesla_switches
    temperature: sensor.marty_mcfly_temperature_sensor_inside
    climate: climate.marty_mcfly_hvac_climate_system
    page_entities:
      columns: 2 #optional
      show_title: 'false' #optional
      entities:
        - entity: sensor.marty_mcfly_range_sensor
        - entity: sensor.marty_mcfly_mileage_sensor
        - entity: binary_sensor.marty_mcfly_charger_sensor
        - entity: sensor.marty_mcfly_charging_rate_sensor
        - entity: binary_sensor.marty_mcfly_parking_brake_sensor
        - entity: binary_sensor.marty_mcfly_online_sensor
    more_entities:
      columns: 2 #optional
      entities:
        - entity: switch.marty_mcfly_update_switch
    addons:
      - name: Batterij
        path: 'dwains-theme/addons/rooms/tesla/battery/page.yaml'
        button_path: 'dwains-theme/addons/rooms/tesla/battery/button.yaml'

  - name: Technische Ruimte
    icon: mdi:water-boiler
    device: switch.cv_hoofdschakelaar