# https://dwainscheeren.github.io/lovelace-dwains-theme/configuration/scenes.html

scenes:
  # - entity: input_boolean.homemode_home
  #   icon: fas:house
  # - entity: input_boolean.homemode_away
  #   icon: fas:running
  - entity: input_boolean.homemode_night
    icon: fas:stars
    name: slapen
  # - entity: input_boolean.homemode_vacation
  #   icon: fas:suitcase
  # - entity: input_boolean.homemode_guest
  #   icon: fas:person
  - entity: input_boolean.scene_bedtime
    icon: fas:bed
  - entity: input_boolean.scene_goodmorning
    icon: fas:coffee
  - entity: input_boolean.scene_normaal
    icon: fas:palette
  - entity: input_boolean.scene_sfeer
    icon: fas:candle-holder
  - entity: input_boolean.scene_helder
    icon: fas:lightbulb-on