########################################
## Droger Status Automations
########################################

- alias: Droger - Status naar Aan
  trigger:
    - platform: numeric_state
      entity_id: sensor.droger_huidig_verbruik
      above: 1
  condition:
    - condition: state
      entity_id: input_select.droger_status
      state: Uit
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.droger_status
        option: Aan

- alias: Droger - Status naar Uit
  trigger:
    - platform: numeric_state
      entity_id: sensor.droger_huidig_verbruik
      below: 1
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: input_select.droger_status
        state: Aan
      - condition: state
        entity_id: input_select.droger_status
        state: Klaar
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.droger_status
        option: Uit

- alias: Droger - Status naar Drogen
  trigger:
    - platform: numeric_state
      entity_id: sensor.droger_huidig_verbruik
      above: 2000
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: input_select.droger_status
        state: Aan
      - condition: state
        entity_id: input_select.droger_status
        state: Uit
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.droger_status
        option: Drogen

- alias: Droger - Status naar Klaar
  trigger:
    - platform: numeric_state
      entity_id: sensor.droger_huidig_verbruik
      below: 100
      for:
        minutes: 5
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_select.droger_status
        state: Drogen
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.droger_status
        option: Klaar
    - service: notify.notifyall
      data:
        message: "De droger is klaar!"
        title: "Droger"

- alias: Droger - Status naar Aan na Klaar
  trigger:
    - platform: state
      entity_id: input_select.droger_status
      to: Klaar
      for:
        minutes: 15
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.droger_status
        option: Aan

- alias: Droger - Staat voor niks Aan
  trigger:
    - platform: state
      entity_id: input_select.droger_status
      to: Aan
      for:
        minutes: 15
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.droger_status
        option: Aan
    - service: notify.notifyall
      data:
        message: "De droger staat nog aan!"
        title: "Droger"

########################################
## Wasmachine Status Automations
########################################

- alias: Wasmachine - Status naar Opwarmen
  trigger:
    - platform: numeric_state
      entity_id: sensor.wasmachine_huidig_verbruik
      above: 1500
  condition:
    - condition: state
      entity_id: input_select.wasmachine_status
      state: Uit
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.wasmachine_status
        option: Opwarmen

- alias: Wasmachine - Status naar Uit
  trigger:
    - platform: numeric_state
      entity_id: sensor.wasmachine_huidig_verbruik
      below: 3
      for:
        minutes: 15
  condition:
    - condition: state
      entity_id: input_select.wasmachine_status
      state: Klaar
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.wasmachine_status
        option: Uit

- alias: Wasmachine - Status naar Wassen
  trigger:
    - platform: numeric_state
      entity_id: sensor.wasmachine_huidig_verbruik
      above: 2
      below: 1500
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: input_select.wasmachine_status
        state: Opwarmen
      - condition: state
        entity_id: input_select.wasmachine_status
        state: Uit
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.wasmachine_status
        option: Wassen

- alias: Wasmachine - Status naar Klaar
  trigger:
    - platform: numeric_state
      entity_id: sensor.wasmachine_huidig_verbruik
      below: 3
      for:
        minutes: 5
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: input_select.wasmachine_status
        state: Wassen
      - condition: state
        entity_id: input_select.wasmachine_status
        state: Opwarmen
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.wasmachine_status
        option: Klaar
    - service: notify.notifyall
      data:
        message: "De wasmachine is klaar!"
        title: "Wasmachine"

########################################
## Gangkachel Status Automations
########################################

- alias: Gangkachel - Status naar Ventileren
  trigger:
    - platform: numeric_state
      entity_id: sensor.gangkachel_huidig_verbruik
      above: 1
      below: 500
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_select.gangkachel_status
        state: Uit
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.gangkachel_status
        option: Ventileren

- alias: Gangkachel - Status naar Afkoelen
  trigger:
    - platform: numeric_state
      entity_id: sensor.gangkachel_huidig_verbruik
      above: 1
      below: 500
  condition:
    condition: or
    conditions:
        - condition: state
          entity_id: input_select.gangkachel_status
          state: Half vermogen
        - condition: state
          entity_id: input_select.gangkachel_status
          state: Vol vermogen
        - condition: and
          conditions:
            - condition: state
              entity_id: input_boolean.gangkachel
              state: 'off'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.gangkachel_status
        option: Afkoelen

- alias: Gangkachel - Status naar Uit
  trigger:
    - platform: numeric_state
      entity_id: sensor.gangkachel_huidig_verbruik
      below: 1
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.gangkachel_status
        option: Uit

- alias: Gangkachel - Status naar Half vermogen
  trigger:
    - platform: numeric_state
      entity_id: sensor.gangkachel_huidig_verbruik
      below: 1500
      above: 500
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.gangkachel_status
        option: Half vermogen

- alias: Gangkachel - Status naar Vol vermogen
  trigger:
    - platform: numeric_state
      entity_id: sensor.gangkachel_huidig_verbruik
      above: 1500
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.gangkachel_status
        option: Vol vermogen
