- alias: 'Donker Uit - Input Boolean gebasseerd op Lux sensor'
  trigger:
    platform: numeric_state
    entity_id: sensor.hue_motion_sensor_1_light_level
    above: 17
    for:
      minutes: 30
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.status_donker

- alias: 'Donker Aan - Input Boolean gebasseerd op Lux sensor'
  trigger:
    platform: numeric_state
    entity_id: sensor.hue_motion_sensor_1_light_level
    below: 15
    for:
      minutes: 10
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.status_donker

- alias: "Timer - Automatisch HA Thema wanneer alarm uit"
  trigger:
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: sun.sun
  action:
    - service_template: frontend.set_theme
      data_template:
        name: >
          {% if states.sun.sun.state == "above_horizon" %}
          synthwave
          {% else %}
          synthwave
          {% endif %}

- alias: "Timer - Notify Me when its time to leave for Work"
  trigger:
  - platform: state
    entity_id: sensor.time_to_leave_for_work
    to: 'True'
    from: 'False'
  condition:
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  action:
    - service: notify.notifyall
      data:
        message: "Het duurt {{ states.sensor.reistijd_naar_werk.state | int | string }} minuten om naar je werk te rijden. Je moet over 10 minuten vertrekken wil je om 8:30u aankomen. De snelste route is via {{ states.sensor.reistijd_naar_werk.attributes.route }}."
        title: "Tijd om te vertrekken"

- alias: "Timer - Notification - Reistijd naar huis"
  trigger:
    platform: time
    at: '17:00:00'
  condition:
    - condition: and
      conditions:
      - condition: state
        entity_id: binary_sensor.workday_sensor
        state: 'on'
      - condition: template
        value_template: "{{ not is_state('device_tracker.tesla_model_3_240589_location_tracker','home') }}"
  action:
    - service: notify.notifyall
      data:
        message: "Het duurt momenteel {{ states.sensor.reistijd_naar_huis.state | int | string }} minuten om naar huis te rijden. De snelste route is via {{ states.sensor.reistijd_naar_huis.attributes.route }}."
        title: "Reistijd naar huis"


- alias: 'Timer - Licht aan wanneer er iemand thuis is'
  trigger:
    platform: state
    entity_id: input_boolean.status_donker
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.homemode_home
        state: 'on'
      - condition: state
        entity_id: group.woonkamer_verlichting
        state: 'off'
      - condition: state
        entity_id: group.keuken_verlichting
        state: 'off'
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: "Woonkamer"
        scene_name: "Sfeerverlichting"
    - service: hue.hue_activate_scene
      data:
        group_name: "Keuken"
        scene_name: "Ontspannen"
    - service: switch.turn_on
      entity_id:
#        - switch.kerstboom_1
#        - switch.kerstboom_2
        - switch.kerstverlichting_buiten
        - switch.veranda_verlichting
    - service: notify.pushover
      data:
        message: "Home Assistant heeft het licht ingeschakeld."
        title: "Verlichting"
        data:
          priority: -1

- alias: 'Timer - Licht aan wanneer er niemand thuis is'
  trigger:
    platform: state
    entity_id: input_boolean.status_donker
    to: 'on'
    for:
      minutes: 30
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.homemode_away
        state: 'on'
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: "Woonkamer"
        scene_name: "Sfeerverlichting"
    - service: hue.hue_activate_scene
      data:
        group_name: "Keuken"
        scene_name: "Sfeerverlichting"
    - service: switch.turn_on
      entity_id:
  #      - switch.kerstboom_1
  #      - switch.kerstboom_2
        - switch.kerstverlichting_buiten
        - switch.veranda_verlichting
    - service: notify.pushover
      data:
        message: "Home Assistant heeft het licht ingeschakeld."
        title: "Verlichting"
        data:
          priority: -1

- alias: 'Timer - Licht uit om 23:30 when wanneer er niemand thuis is'
  trigger:
    platform: time
    at: '23:30:00'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.homemode_away
        state: 'on'
      - condition: state
        entity_id: input_boolean.homemode_guest
        state: 'off'
  action:
    - service: homeassistant.turn_off
      entity_id:
        - group.woonkamer_verlichting
        - group.keuken_verlichting
    - service: switch.turn_off
      entity_id:
  #      - switch.kerstboom_1
  #      - switch.kerstboom_2
        - switch.kerstverlichting_buiten
    - service: notify.pushover
      data:
        message: "Home Assistant heeft het licht uitgeschakeld."
        title: "Verlichting"
        data:
          priority: -1

- alias: 'Timer - Start HomeKit'
  trigger:
    - platform: homeassistant
      event: start
  action:
    - delay: 00:01  # Waits 1 minute
    - service: homekit.start

- alias: 'Timer - Buitenverlichting aan wanneer donker'
  trigger:
    platform: state
    entity_id: binary_sensor.donker
    to: 'on'
  action:
    - service: switch.turn_on
      entity_id: 
        - switch.veranda_verlichting




- alias: 'Hek openen door drukknop, Tesla of iOS'
  trigger:
    - platform: state
      entity_id: binary_sensor.keuken_hekopener
      to: 'on'
    - platform: state
      entity_id: binary_sensor.woonkamer_hekopener
      to: 'on'
    - platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: OPEN_HEK
  action:
     - service: switch.turn_on
       entity_id:
         - switch.looppoort_deurbel_relay_1
     - service: tts.google_say
       entity_id: media_player.google_home_mini
       data:
         message: 'Hek wordt geopend'

- alias: 'Pushbutton - Nachtkastjes - Bedtijd'
  trigger:
    - platform: state
      entity_id: binary_sensor.nachtkastje_martien
      to: 'on'
    - platform: state
      entity_id: binary_sensor.nachtkastje_deborah
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.scene_bedtime
        state: 'off'
      - condition: state
        entity_id: input_boolean.homemode_night
        state: 'off'
  action:
     - service: input_boolean.turn_on
       entity_id:
         - input_boolean.scene_bedtime

- alias: 'Pushbutton - Nachtkastjes - Nachtmode'
  trigger:
    - platform: state
      entity_id: binary_sensor.nachtkastje_martien
      to: 'on'
    - platform: state
      entity_id: binary_sensor.nachtkastje_deborah
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.scene_bedtime
        state: 'on'
      - condition: state
        entity_id: input_boolean.homemode_night
        state: 'off'
  action:
     - service: input_boolean.turn_on
       entity_id:
         - input_boolean.homemode_night

- alias: 'Pushbutton - Nachtkastjes - Nachtlampje Aan'
  trigger:
    - platform: state
      entity_id: binary_sensor.nachtkastje_martien
      to: 'on'
    - platform: state
      entity_id: binary_sensor.nachtkastje_deborah
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.scene_bedtime
        state: 'off'
      - condition: state
        entity_id: input_boolean.homemode_night
        state: 'on'
      - condition: state
        entity_id: group.slaapkamer_spots
        state: 'off'
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: "Slaapkamer"
        scene_name: "Nachtlampje"

- alias: 'Pushbutton - Nachtkastjes - Nachtlampje Uit'
  trigger:
    - platform: state
      entity_id: binary_sensor.nachtkastje_martien
      to: 'on'
    - platform: state
      entity_id: binary_sensor.nachtkastje_deborah
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.scene_bedtime
        state: 'off'
      - condition: state
        entity_id: input_boolean.homemode_night
        state: 'on'
      - condition: state
        entity_id: group.slaapkamer_spots
        state: 'on'
  action:
    - service: homeassistant.turn_off
      entity_id: group.slaapkamer_spots

########################################
## Notificatoins Only
########################################
- alias: 'Notification - Doorbell pressed'
  trigger:
    - platform: event
      event_type: button_pressed
      event_data: {"entity_id": "switch.deurbel"}
    - platform: event
      event_type: doorbird_looppoort_deurbel_button
  action:
    - service: notify.notifyall
      data:
        message: "De deurbel gaat!"
        title: "Ding! Dong!"
        data:
          push:
            badge: 0 ## This will remove the badge/app icon number ##
            category: 'camera'
          entity_id: camera.looppoort_deurbel_live

- alias: 'Notification - Landroid Alarm'
  trigger:
    - platform: numeric_state
      entity_id: landroid.no_of_alarms
      above: 0
  action:
    - service: notify.pushover
      data_template:
        message: "Warning: The lawnmower is reporting an error."
        title: "Lawnmower Error"
    - service: notify.notifyme
      data:
        message: "Today at {{(now().strftime('%s') | int | timestamp_custom('%H:%M'))}} the lawnmower had reported an error."

- alias: "Notification - Home Assistant Update Available"
  trigger:
    - platform: state
      entity_id: updater.updater
  action:
    - service: notify.notifyall
      data:
        message: "Home Assistant versie {{ states.updater.updater.state }} is nu bechikbaar."
        title: "HA Update beschikbaar"
    - service: persistent_notification.create
      data:
        message: "Home Assistant versie {{ states.updater.updater.state }} is nu bechikbaar."
        title: "HA Update beschikbaar"


- alias: "Notification - Home Assistant Startup"
  trigger:
    - platform: homeassistant
      event: start
  action:
    - service: notify.notifyall
      data:
        message: "Home Assistant is sinds {{(now().strftime('%s') | int | timestamp_custom('%H:%M'))}} weer online."
        title: "HA Online"
    - service: persistent_notification.create
      data:
        message: "Home Assistant is sinds {{(now().strftime('%s') | int | timestamp_custom('%H:%M'))}} weer online."
        title: "HA Online"

- alias: "Notification - Home Assistant Shutdown"
  trigger:
    - platform: homeassistant
      event: shutdown
  action:
    - service: notify.notifyall
      data:
        message: "Waarschuwing: Home Assistant wordt herstart."
        title: "HA Herstart"
    - service: persistent_notification.create
      data:
        message: "Waarschuwing: Home Assistant wordt herstart."
        title: "HA Herstart"

- alias: "IFTTT Webhook verzoeken"
  trigger:
    platform: event
    event_type: ifttt_webhook_received
    event_data:
      action: call_service
  action:
    service_template: '{{ trigger.event.data.service }}'
    data_template:
      entity_id: '{{ trigger.event.data.entity_id }}'
