- alias: 'Timer - Turn off Badkamerfan after 60min.'
  trigger:
    - platform: state
      entity_id: switch.badkamerfan_sonoff
      to: 'on'
      for:
        minutes: 60
  action:
    - service: homeassistant.turn_off
      data:
        entity_id:
          - switch.badkamerfan_sonoff

- alias: 'Timer - Turn on Badkamerfan after 7min.'
  trigger:
    - platform: state
      entity_id: group.badkamer_spots
      to: 'on'
      for:
        minutes: 7
  action:
    - service: homeassistant.turn_on
      data:
        entity_id:
          - switch.badkamerfan_sonoff

- alias: 'Timer - Turn off Badkamerfan after lights off for 30min.'
  trigger:
    - platform: state
      entity_id: group.badkamer_spots
      to: 'off'
      for:
        minutes: 30
  action:
    - service: homeassistant.turn_off
      data:
        entity_id:
          - switch.badkamerfan_sonoff