########################################
## Doorbell Automations
########################################

- alias: 'Doorbell - Pause Woonkamer TV on Doorbell'
  trigger:
    - platform: event
      event_type: button_pressed
      event_data: {"entity_id": "switch.deurbel"}
    - platform: event
      event_type: doorbird_looppoort_deurbel_button
  condition:
    - condition: state
      entity_id:  media_player.woonkamer_live_tv
      state: 'playing'
  action:
    - service: media_player.media_pause
      entity_id:  media_player.woonkamer_live_tv

- alias: 'Doorbell - Play doorbell chime via Sonos'
  trigger:
    - platform: event
      event_type: button_pressed
      event_data: {"entity_id": "switch.deurbel"}
    - platform: event
      event_type: doorbird_looppoort_deurbel_button
  condition:
    condition: state
    entity_id: group.personen
    state: 'home'
  action:
    - service: media_player.volume_set
      entity_id:
        - media_player.google_home_mini
      data:
        volume_level: 0.60
    - service: media_player.play_media
      data_template:
        entity_id:
          - media_player.google_home_mini
        media_content_id: https://martiendekleijn.duckdns.org:8123/local/doorbell.mp3
        media_content_type: music
    - delay: '00:00:13'
    - service: media_player.volume_set
      entity_id:
        - media_player.google_home_mini
      data:
        volume_level: 0.40