- alias: 'Download automations - Notify on Transmission downloads paused'
  trigger:
    platform: numeric_state
    entity_id: sensor.transmission_paused_torrents
    above: 0
    for:
      minutes: 10
  action:
    - service: notify.martien
      data:
        message: "Transmission heeft gepauzeerde downloads!"
        title: "Downloads"

    