- alias: 'Download automations - Notify on Transmission downloads paused'
  trigger:
    platform: numeric_state
    entity_id: sensor.transmission_paused_torrents
    above: 0
  action:
    - service: notify.notifyall
      data:
        message: "Transmission heeft gepauzeerde downloads!"
        title: "Downloads"

    