- alias: 'Hek openen door drukknop, Tesla of iOS'
  trigger:
    - platform: state
      entity_id: binary_sensor.keuken_hekopener
      to: 'on'
    - platform: state
      entity_id: binary_sensor.woonkamer_hekopener
      to: 'on'
    - platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: OPEN_HEK
  action:
    - service: switch.turn_on
      entity_id:
        - switch.deurbel_relay_1
    - service: tts.google_say
      entity_id: media_player.google_home_mini
      data:
        message: 'Hek wordt geopend'

- alias: 'Pushbutton - Nachtkastjes - Bedtijd'
  trigger:
    - platform: state
      entity_id: binary_sensor.nachtkastje_martien
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.scene_bedtime
        state: 'off'
      - condition: state
        entity_id: input_boolean.homemode_night
        state: 'off'
  action:
    - service: input_boolean.turn_on
      entity_id:
        - input_boolean.scene_bedtime

- alias: 'Pushbutton - Nachtkastjes - Nachtmode'
  trigger:
    - platform: state
      entity_id: binary_sensor.nachtkastje_martien
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.scene_bedtime
        state: 'on'
      - condition: state
        entity_id: input_boolean.homemode_night
        state: 'off'
  action:
    - service: input_boolean.turn_on
      entity_id:
        - input_boolean.homemode_night

- alias: 'Pushbutton - Nachtkastjes - Nachtlampje Aan'
  trigger:
    - platform: state
      entity_id: binary_sensor.nachtkastje_martien
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.scene_bedtime
        state: 'off'
      - condition: state
        entity_id: input_boolean.homemode_night
        state: 'on'
      - condition: state
        entity_id: group.slaapkamer_spots
        state: 'off'
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: "Slaapkamer"
        scene_name: "Nachtlampje"

- alias: 'Pushbutton - Nachtkastjes - Nachtlampje Uit'
  trigger:
    - platform: state
      entity_id: binary_sensor.nachtkastje_martien
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.scene_bedtime
        state: 'off'
      - condition: state
        entity_id: input_boolean.homemode_night
        state: 'on'
      - condition: state
        entity_id: group.slaapkamer_spots
        state: 'on'
  action:
    - service: homeassistant.turn_off
      entity_id: group.slaapkamer_spots


# Overloop / trap      
- alias: 'Fysieke knop: Overloop Activeer Bedtijd'
  trigger:
    - platform: state
      entity_id: binary_sensor.overloop_sceneschakelaar
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.homemode_night
        state: 'off'
      - condition: state
        entity_id: input_boolean.scene_bedtime
        state: 'off'
      - condition: or
        conditions:
          - condition: state
            entity_id: binary_sensor.avond
            state: 'on'
          - condition: state
            entity_id: binary_sensor.nacht
            state: 'on'
  action:
    - service: input_boolean.turn_on
      entity_id:
        - input_boolean.scene_bedtime

- alias: 'Fysieke knop: Overloop Activeer Home'
  trigger:
    - platform: state
      entity_id: binary_sensor.overloop_sceneschakelaar
      to: 'on'
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: input_boolean.homemode_night
        state: 'on'
      - condition: state
        entity_id: input_boolean.scene_bedtime
        state: 'on'
  action:
    - service: input_boolean.turn_on
      entity_id:
        - input_boolean.homemode_home

# KELDER
- alias: 'Fysieke knop: Kelder Lichtschakelaar'
  trigger:
    - platform: state
      entity_id: binary_sensor.kelder_lichtschakelaar
      to: 'on'
  action:
    - service: switch.toggle
      entity_id: switch.kelderlicht

- alias: 'Fysieke knop: Kelder Pompschakelaar'
  trigger:
    - platform: state
      entity_id: binary_sensor.kelder_pompschakelaar
      to: 'on'
  action:
    - service: switch.toggle
      entity_id: switch.kelderpomp