########################################
##
########################################
- alias: "Verwarming uit bij openen badkamerraam"
  trigger:
    - platform: state
      entity_id: binary_sensor.badkamerraam
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.homemode_home
        state: 'on'
      - condition: numeric_state
        entity_id: sensor.buiten_temperature
        below: 19
  action:
    - service: climate.set_temperature
      data:
        entity_id: climate.netatmo_badkamer
        temperature: 15
    - service: homeassistant.turn_on
      data:
        entity_id:
          - switch.badkamerfan_sonoff
    - service: notify.martien
      data:
        message: "De thermostaat in de badkamer is lager gezet en de ventilator aan omdat het raam is geopend."
        title: "Verwarming lager"

- alias: "Sync Gangkachel - Temperatuur met Badkamer Thermostaat"
  trigger:
    platform: template
    value_template: "{{ state_attr('climate.netatmo_badkamer', 'temperature') != state_attr('climate.gang', 'temperature') }}"
  condition:
    - condition: state
      entity_id: input_boolean.gangkachel_schema
      state: 'on'
  action:
    - service: climate.set_temperature
      data_template:
        entity_id: climate.gang
        temperature: "{{ state_attr('climate.netatmo_badkamer', 'temperature') }}"

- alias: "Sync Gangkachel - Schema Aan"
  trigger:
    platform: state
    entity_id: input_boolean.gangkachel_schema
    to: 'on'
  action:
    - service: climate.set_temperature
      data_template:
        entity_id: climate.gang
        temperature: "{{ state_attr('climate.netatmo_badkamer', 'temperature') }}"

- alias: "Sync Gangkachel - Schema Uit"
  trigger:
    platform: state
    entity_id: input_boolean.gangkachel_schema
    to: 'off'
  action:
    - service: climate.set_temperature
      data:
        entity_id: climate.gang
        temperature: 7

- alias: 'Timer - Turn on Gangkachel Sonoff after 5sec.'
  trigger:
    - platform: state
      entity_id: switch.gangkachel_sonoff
      to: 'off'
      for:
        seconds: 5
  action:
    - service: climate.set_temperature
      data:
        entity_id: climate.gang
        temperature: 7
    - service: homeassistant.turn_off
      data:
        entity_id:
          - input_boolean.gangkachel
    - service: homeassistant.turn_on
      data:
        entity_id:
          - switch.gangkachel_sonoff


- alias: 'Time - Gangkachel harde reset na 2 uur'
  trigger:
    - platform: numeric_state
      entity_id: sensor.gangkachel_huidig_verbruik
      above: 10
      for:
        minutes: 120
  action:
    - service: homeassistant.turn_off
      data:
        entity_id:
          - switch.gangkachel_sonoff

########################################
## Gangkachel Thermostaat Automations
########################################

- alias: 'Gangkachel - Ingeschakeld door HA thermostaat'
  trigger:
    - platform: state
      entity_id: input_boolean.gangkachel
      to: 'on'
  condition:
    - condition: state
      entity_id: input_select.gangkachel_status
      state: Uit
  action:
    - service: switch.turn_on
      entity_id: switch.gangkachel_aanuit

- alias: 'Gangkachel - Instellen bij Ventileren'
  trigger:
    - platform: state
      entity_id: input_boolean.gangkachel
      to: 'on'
      for:
        seconds: 20
  condition:
    - condition: state
      entity_id: input_select.gangkachel_status
      state: Ventileren
  action:
    - service: switch.turn_on
      entity_id: switch.gangkachel_highlow

- alias: 'Gangkachel - Instellen bij Half vermogen'
  trigger:
    - platform: state
      entity_id: input_boolean.gangkachel
      to: 'on'
      for:
        seconds: 30
  condition:
    - condition: state
      entity_id: input_select.gangkachel_status
      state: Half vermogen
  action:
    - service: switch.turn_on
      entity_id: switch.gangkachel_highlow

- alias: 'Gangkachel - Instellen bij Afkoelen'
  trigger:
    - platform: state
      entity_id: input_boolean.gangkachel
      to: 'on'
      for:
        seconds: 20
  condition:
    - condition: state
      entity_id: input_select.gangkachel_status
      state: Afkoelen
  action:
    - service: switch.turn_on
      entity_id: switch.gangkachel_aanuit

- alias: 'Gangkachel - Thermostaat Uitgeschakeld bij status Vermogen'
  trigger:
    - platform: state
      entity_id: input_boolean.gangkachel
      to: 'off'
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: input_select.gangkachel_status
        state: Half vermogen
      - condition: state
        entity_id: input_select.gangkachel_status
        state: Vol vermogen
  action:
    - service: switch.turn_off
      entity_id: switch.gangkachel_aanuit

- alias: 'Gangkachel - Terug naar Half vermogen na 30min.'
  trigger:
    - platform: state
      entity_id: input_select.gangkachel_status
      to: Vol vermogen
      for:
        minutes: 30
  action:
    - service: switch.turn_on
      entity_id: switch.gangkachel_highlow
    - delay: 00:00:05
    - service: switch.turn_on
      entity_id: switch.gangkachel_highlow
