########################################
## Automatisch Klimaat
########################################
- alias: "Klimaat: Thermostaat programma aan wanneer onderweg naar huis"
  trigger:
    platform: numeric_state
    entity_id: proximity.home
    below: 10
    above: 1
  condition:
    - condition: state
      entity_id: input_boolean.homemode_away
      state: "on"
    - "{{ is_state_attr('proximity.home', 'dir_of_travel', 'towards') }}"
  action:
    - service: climate.set_hvac_mode
      data:
        entity_id: climate.netatmo_woonkamer
        hvac_mode: 'auto'
    - service: climate.set_hvac_mode
      data:
        entity_id: climate.gang_vloerverwarming
        hvac_mode: 'auto'
    - service: climate.set_hvac_mode
      data:
        entity_id: climate.badkamer_vloerverwarming
        hvac_mode: 'auto'
    - service: notify.martien
      data:
        title: "🌡 Klimaat"
        message: "De verwarming is automatisch ingeschakeld."

- alias: "Klimaat: Verwarming uit bij openen badkamerraam"
  trigger:
    - platform: state
      entity_id: binary_sensor.badkamerraam
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.homemode_home
        state: 'on'
      - condition: numeric_state
        entity_id: sensor.dark_sky_temperature
        below: 17
  action:
    - service: climate.set_temperature
      data:
        entity_id: climate.netatmo_badkamer
        temperature: 14
    - service: climate.set_temperature
      data:
        entity_id: climate.netatmo_gang
        temperature: 14
    - service: notify.martien
      data:
        message: "De thermostaat in de badkamer en gang is lager gezet omdat het raam is geopend."
        title: "🌡 Klimaat"

- alias: "Klimaat: Vorstvrij bij vakantie"
  trigger:
    - platform: state
      entity_id: input_boolean.homemode_vacation
      to: 'on'
  action:
    - service: climate.set_preset_mode
      data:
        entity_id: climate.netatmo_woonkamer
        preset_mode: "Frost Guard"

- alias: 'Klimaat: Scene Opstaan'
  trigger:
    - platform: state
      entity_id: input_boolean.scene_goodmorning
      to: 'on'
  condition:
  - condition: template
    value_template: "{{ states.climate.netatmo_woonkamer.attributes['temperature'] | int < 17 }}"
  action:
    - service: climate.set_temperature
      data:
        entity_id: climate.netatmo_woonkamer
        temperature: 17
    - service: climate.set_temperature
      data:
        entity_id: climate.netatmo_keuken
        temperature: 17
    - service: climate.set_temperature
      data:
        entity_id: climate.netatmo_badkamer
        temperature: 18
    - service: climate.set_temperature
      data:
        entity_id: climate.netatmo_gang
        temperature: 17
            
- alias: 'Klimaat: Scene Naar Bed'
  trigger:
    - platform: state
      entity_id: input_boolean.scene_bedtime
      to: 'on'
  action:
    - service: climate.set_temperature
      data:
        entity_id: climate.netatmo_woonkamer
        temperature: 14
    - service: climate.set_temperature
      data:
        entity_id: climate.netatmo_keuken
        temperature: 14
    - service: climate.set_temperature
      data:
        entity_id: climate.netatmo_badkamer
        temperature: 12
    - service: climate.set_temperature
      data:
        entity_id: climate.netatmo_gang
        temperature: 12
    - service: climate.set_temperature
      data:
        entity_id: climate.netatmo_slaapkamer
        temperature: 14


########################################
## Badkamer ventilatie
########################################
- alias: 'Klimaat: Turn off Badkamerfan after 60min.'
  trigger:
    - platform: state
      entity_id: switch.badkamerfan_sonoff
      to: 'on'
      for:
        minutes: 60
  action:
    - service: homeassistant.turn_off
      data:
        entity_id:
          - switch.badkamerfan_sonoff


- alias: 'Klimaat: Badkamer ventilator aan bij hoge luchtvochtigheid of licht aan'
  trigger:
    - platform: numeric_state
      entity_id: sensor.humidity_badkamer
      above: 75
    - platform: state
      entity_id: light.badkamer_spotjes
      to: 'on'
      for:
        minutes: 7
  condition:
    - condition: numeric_state
      entity_id: sensor.humidity_badkamer
      above: 75
  action:
    - service: homeassistant.turn_on
      data:
        entity_id:
          - switch.badkamerfan_sonoff

- alias: 'Klimaat: Badkamer ventilator uit bij normale luchtvochtigheid'
  trigger:
    - platform: numeric_state
      entity_id: sensor.humidity_badkamer
      below: 70
      for:
        minutes: 10
  action:
    - service: homeassistant.turn_off
      data:
        entity_id:
          - switch.badkamerfan_sonoff


- alias: 'Klimaat: Serverrack fan aan bij hoge CPU temp'
  trigger:
    - platform: numeric_state
      entity_id: sensor.glances_package_id_0_temperature_2
      above: 65
      for:
        minutes: 1
  action:
    - service: homeassistant.turn_on
      data:
        entity_id:
          - switch.server_rack_fan

- alias: 'Klimaat: Serverrack fan uit bij normale CPU temp'
  trigger:
    - platform: numeric_state
      entity_id: sensor.glances_package_id_0_temperature_2
      below: 60
      for:
       minutes: 5
  action:
    - service: homeassistant.turn_off
      data:
        entity_id:
          - switch.server_rack_fan