- alias: 'Alarm - Water lekkage gedetecteerd in WC Boven'
  trigger:
    platform: state
    entity_id: binary_sensor.lekkage_wc_boven
    to: 'on'
  action:
    - service: notify.notifyall
      data_template:
        message: "{{ trigger.to_state.attributes.friendly_name }} gedetecteerd!!"
        title: "Water lekkage gedetecteerd!!"
    - service: script.speak
      data:
        what: 'Waarschuwing! Er is water lekkage gedetecteerd in de WC boven!'

- alias: 'Alarm - Water lekkage gedetecteerd in badkamer'
  trigger:
    platform: state
    entity_id: binary_sensor.lekkage_badkamer
    to: 'on'
  action:
    - service: notify.notifyall
      data_template:
        message: "{{ trigger.to_state.attributes.friendly_name }} gedetecteerd!!"
        title: "Water lekkage gedetecteerd!!"
    - service: script.speak
      data:
        what: 'Waarschuwing! Er is water lekkage gedetecteerd in de badkamer!'