########################################
## Motion Automations
########################################

- alias: 'Motion - Ganglight aan bij Beweging'
  trigger:
    - platform: state
      entity_id: binary_sensor.gang_motion
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.homemode_home
        state: 'on'
      - condition: state
        entity_id: input_boolean.status_donker
        state: 'on'
  action:
    - service: switch.turn_on
      entity_id: switch.ganglicht

- alias: 'Motion - Ganglight uit bij geen beweging'
  trigger:
    - platform: state
      entity_id: binary_sensor.gang_motion
      to: 'off'
      for:
        minutes: 10
  action:
     - service: switch.turn_off
       entity_id:
         - switch.ganglicht

- alias: 'Motion - Keukenlicht naar normaal bij beweging'
  trigger:
    - platform: state
      entity_id: binary_sensor.keuken_motion
      to: 'on'
    - platform: state
      entity_id: binary_sensor.keukendeur
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.homemode_home
        state: 'on'
      - condition: state
        entity_id: input_boolean.status_donker
        state: 'on'
      - condition: state
        entity_id: light.keuken_5
        state: 'on'
      - condition: state
        entity_id: light.keuken_4
        state: 'on'
      - condition: state
        entity_id: light.keuken_3
        state: 'off'
      - condition: state
        entity_id: light.keuken_2
        state: 'off'
      - condition: state
        entity_id: light.keuken_1
        state: 'off'
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: "Keuken"
        scene_name: "Normaal"

- alias: 'Motion - Keukenlicht naar sfeer bij geen beweging'
  trigger:
    - platform: state
      entity_id: binary_sensor.keuken_motion
      to: 'off'
      for:
        minutes: 10
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.homemode_home
        state: 'on'
      - condition: state
        entity_id: input_boolean.status_donker
        state: 'on'
      - condition: state
        entity_id: light.keuken_5
        state: 'on'
      - condition: state
        entity_id: light.keuken_4
        state: 'on'
      - condition: state
        entity_id: light.keuken_3
        state: 'on'
      - condition: state
        entity_id: light.keuken_2
        state: 'on'
      - condition: state
        entity_id: light.keuken_1
        state: 'on'
      - condition: state
        entity_id: light.eetkamertafel
        state: 'off'
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: "Keuken"
        scene_name: "Sfeerverlichting"