########################################
## Presence based automations
########################################
- alias: 'Presence - Turn on away mode'
  trigger:
    - platform: state
      entity_id: group.personen
      to: 'not_home'
      for:
        minutes: 60
  condition:
    - condition: state
      entity_id: input_boolean.homemode_guest
      state: 'off'
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.homemode_away

- alias: 'Presence - Turn on home mode'
  trigger:
    - platform: state
      entity_id: group.personen
      to: 'home'
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.homemode_home

- alias: 'Presence - Turn on guest mode'
  trigger:
    - platform: state
      entity_id: group.gasten
      to: 'home'
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.homemode_guest

- alias: 'Presence - Turn off guest mode when someone home'
  trigger:
    - platform: state
      entity_id: group.gasten
      to: 'not_home'
      for:
        minutes: 30 
  condition:
    - condition: state
      state: home
      entity_id: group.personen
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.homemode_home

- alias: 'Presence - Turn off guest mode when no one home'
  trigger:
    - platform: state
      entity_id: group.gasten
      to: 'not_home'
      for:
        minutes: 480
  condition:
    - condition: state
      state: not_home
      entity_id: group.personen
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.homemode_away