- alias: 'Mediastart - Radio 2'
  trigger:
    platform: state
    entity_id: input_boolean.media_start_radio2
    to: 'on'
  action:
    - service: script.sonos_play_source
      data:
        source: "NPO Radio 2 92.9 (Pop)"

- alias: 'Mediastart - Radio 3FM'
  trigger:
    platform: state
    entity_id: input_boolean.media_start_3fm
    to: 'on'
  action:
    - service: script.sonos_play_source
      data:
        source: "NPO 3FM 96.5 (Top-40-Pop)"

- alias: 'Mediastart - Radio 10'
  trigger:
    platform: state
    entity_id: input_boolean.media_start_radio10
    to: 'on'
  action:
    - service: script.sonos_play_source
      data:
        source: "Radio 10 88.1 (Classic Hits)"

- alias: 'Mediastart - Skyradio'
  trigger:
    platform: state
    entity_id: input_boolean.media_start_skyradio
    to: 'on'
  action:
    - service: script.sonos_play_source
      data:
        source: "Sky Radio 101 FM 101.2 (Pop)"

- alias: 'Mediastart - Sublime FM'
  trigger:
    platform: state
    entity_id: input_boolean.media_start_sublimefm
    to: 'on'
  action:
    - service: script.sonos_play_source
      data:
        source: "Sublime FM"