- alias: 'Homemode - Reset Scene Input_Booleans after 180 seconds'
  trigger:
    platform: state
    entity_id:
      - input_boolean.scene_bedtime
      - input_boolean.scene_goodmorning
      - input_boolean.scene_sfeer
      - input_boolean.scene_helder
      - input_boolean.scene_normaal
      - input_boolean.scene_aantafel
      - input_boolean.scene_badtijd
    to: 'on'
    for:
      seconds: 180
  action:
    - service: homeassistant.turn_off
      entity_id:
        - input_boolean.scene_bedtime
        - input_boolean.scene_goodmorning
        - input_boolean.scene_sfeer
        - input_boolean.scene_helder
        - input_boolean.scene_normaal
        - input_boolean.scene_aantafel
        - input_boolean.scene_badtijd
    - service: input_select.select_option
      data:
        entity_id: input_select.current_scene
        option: "Geen actief"

- alias: 'Scene - Bedtijd aan'
  trigger:
    - platform: state
      entity_id: input_boolean.scene_bedtime
      to: 'on'
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.text_to_speech_mute
    - service: hue.hue_activate_scene
      data:
        group_name: "Slaapkamer"
        scene_name: "Ontspannen"
    - service: homeassistant.turn_off
      entity_id:
        - light.woonkamer_verlichting
        - light.keuken_verlichting
        - switch.veranda_verlichting
        - switch.kaku_switch_3
        - switch.kaku_switch_1
        - input_boolean.gangkachel_schema
    - service: climate.set_temperature
      data:
        entity_id: climate.netatmo_woonkamer
        temperature: 14
    - service: media_player.media_pause
      data_template:
        entity_id:
          - media_player.woonkamer
          - media_player.badkamer
          - media_player.keuken
          - media_player.tvkamer
    - service: media_player.volume_set
      data_template:
        volume_level: '0.02'
        entity_id:
          - media_player.woonkamer
          - media_player.badkamer
          - media_player.keuken
          - media_player.tvkamer
    - service: input_select.select_option
      data:
        entity_id: input_select.current_scene
        option: "Bedtijd"

- alias: 'Scene - Opstaan aan'
  trigger:
    - platform: state
      entity_id: input_boolean.scene_goodmorning
      to: 'on'
  action:
    - service: homeassistant.turn_off
      entity_id:
        - input_boolean.scene_night
        - input_boolean.scene_bedtime
        - input_boolean.scene_sfeer
    - service: homeassistant.turn_on
      entity_id:
        - switch.plex_server
        - switch.tv_meubel_tuya
        - input_boolean.homemode_home
        - input_boolean.gangkachel_schema
        - switch.kaku_switch_3
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.text_to_speech_mute
    - service: media_player.volume_set
      data_template:
        volume_level: '0.02'
        entity_id:
          - media_player.woonkamer
          - media_player.badkamer
          - media_player.keuken
          - media_player.tvkamer
    - service: input_select.select_option
      data:
        entity_id: input_select.current_scene
        option: "Opstaan"

- alias: 'Scene - Opstaan aan - Verlichting'
  trigger:
    - platform: state
      entity_id: input_boolean.scene_goodmorning
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.status_donker
      state: 'on'
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: "Woonkamer"
        scene_name: "Opstaan"
    - service: hue.hue_activate_scene
      data:
        group_name: "Keuken"
        scene_name: "Sfeerverlichting"

- alias: 'Scene - Opstaan aan - Verwarming'
  trigger:
    - platform: state
      entity_id: input_boolean.scene_goodmorning
      to: 'on'
  condition:
  - condition: template
    value_template: "{{ states.climate.netatmo_woonkamer.attributes['temperature'] | int < 17 }}"
  action:
    - service: homeassistant.turn_on
      entity_id:
        - input_boolean.gangkachel_schema
    - service: climate.set_temperature
      data:
        entity_id: climate.netatmo_woonkamer
        temperature: 17.5

- alias: 'Scene - Sfeer aan'
  trigger:
    - platform: state
      entity_id: input_boolean.scene_sfeer
      to: 'on'
  action:
    - service: homeassistant.turn_off
      entity_id:
        - input_boolean.scene_helder
        - switch.ganglicht
        - light.badkamer_spots
    - service: hue.hue_activate_scene
      data:
        group_name: "Woonkamer"
        scene_name: "Sfeerverlichting"
    - service: hue.hue_activate_scene
      data:
        group_name: "Keuken"
        scene_name: "Sfeerverlichting"
    - service: input_select.select_option
      data:
        entity_id: input_select.current_scene
        option: "Geen actief"

- alias: 'Scene - Helder aan'
  trigger:
    - platform: state
      entity_id: input_boolean.scene_helder
      to: 'on'
  action:
    - service: homeassistant.turn_off
      entity_id:
        - input_boolean.scene_sfeer
        - input_boolean.scene_goodmorning
    - service: hue.hue_activate_scene
      data:
        group_name: "Woonkamer"
        scene_name: "Helder"
    - service: hue.hue_activate_scene
      data:
        group_name: "Keuken"
        scene_name: "Helder"
    - service: input_select.select_option
      data:
        entity_id: input_select.current_scene
        option: "Helder"

- alias: 'Scene - Badtijd Aan'
  trigger:
    - platform: state
      entity_id: input_boolean.scene_badtijd
      to: 'on'
  # condition:
  #   - condition: state
  #     entity_id: input_boolean.status_donker
  #     state: 'on'
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: "Badkamer"
        scene_name: "Ontspannen"
    - service: climate.set_temperature
      data:
        entity_id: climate.netatmo_badkamer
        temperature: 18.5
    - service: homeassistant.turn_on
      entity_id:
        - input_boolean.gangkachel_schema
    - service: input_select.select_option
      data:
        entity_id: input_select.current_scene
        option: "Badtijd"

- alias: 'Scene - Aan tafel'
  trigger:
    - platform: state
      entity_id: input_boolean.scene_aantafel
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.status_donker
      state: 'on'
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: "Keuken"
        scene_name: "Aan Tafel"
    - service: hue.hue_activate_scene
      data:
        group_name: "Woonkamer"
        scene_name: "Sfeerverlichting"
    - service: input_select.select_option
      data:
        entity_id: input_select.current_scene
        option: "Aan tafel"

- alias: 'Scene - Normaal'
  trigger:
    - platform: state
      entity_id: input_boolean.scene_aantafel
      to: 'on'
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: "Woonkamer"
        scene_name: "Normaal"
    - service: input_select.select_option
      data:
        entity_id: input_select.current_scene
        option: "Normaal"