- alias: 'Homemode - Reset Scene Input_Booleans after 180 seconds'
  trigger:
    platform: state
    entity_id:
      - input_boolean.scene_bedtime
      - input_boolean.scene_goodmorning
      - input_boolean.scene_sfeer
      - input_boolean.scene_helder
      - input_boolean.scene_normaal
      - input_boolean.scene_aantafel
      - input_boolean.scene_badtijd
      - input_boolean.scene_thuiswerken
    to: 'on'
    for:
      seconds: 180
  action:
    - service: homeassistant.turn_off
      entity_id:
        - input_boolean.scene_bedtime
        - input_boolean.scene_goodmorning
        - input_boolean.scene_sfeer
        - input_boolean.scene_helder
        - input_boolean.scene_normaal
        - input_boolean.scene_aantafel
        - input_boolean.scene_badtijd
        - input_boolean.scene_thuiswerken

- alias: "Scene: Opstaan elke ochtend beweging"
  trigger:
    platform: state
    entity_id:
      - binary_sensor.woonkamer_motion
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.homemode_night
        state: 'on'
      - condition: state
        entity_id: binary_sensor.ochtend
        state: 'on'
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: 
          - input_boolean.scene_goodmorning
        
- alias: 'Scene - Bedtijd aan'
  trigger:
    - platform: state
      entity_id: input_boolean.scene_bedtime
      to: 'on'
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.text_to_speech_mute
    - service: homeassistant.turn_off
      entity_id:
        - group.woonkamer_verlichting
        - group.keuken_verlichting
        - group.badkamer_spots
        - group.kantoor_verlichting
        - switch.veranda_verlichting
        - light.hue_play_all
        - switch.ganglicht
        - switch.kelderlicht
        - switch.bureau_martien
        - switch.kerstboom
        #- switch.kerstverlichting_dakgoot
        #- switch.kerstboom #kerstboom
    - service: media_player.media_pause
      data_template:
        entity_id:
          - media_player.woonkamer
          - media_player.badkamer
          - media_player.keuken
          - media_player.tvkamer
    - service: media_player.volume_set
      data_template:
        volume_level: '0.02'
        entity_id:
          - media_player.woonkamer
          - media_player.badkamer
          - media_player.keuken
          - media_player.tvkamer
          - media_player.kantoor
          - media_player.veranda

- alias: 'Scene - Opstaan aan'
  trigger:
    - platform: state
      entity_id: input_boolean.scene_goodmorning
      to: 'on'
  action:
    - service: homeassistant.turn_off
      entity_id:
        - input_boolean.scene_night
        - input_boolean.scene_bedtime
        - input_boolean.scene_sfeer
    - service: homeassistant.turn_on
      entity_id:
        - input_boolean.homemode_home
        - switch.bureau_martien
        - switch.kerstboom
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.text_to_speech_mute
    - service: media_player.volume_set
      data_template:
        volume_level: '0.02'
        entity_id:
          - media_player.woonkamer
          - media_player.badkamer
          - media_player.keuken
          - media_player.tvkamer
          - media_player.kantoor
          - media_player.veranda
          - media_player.slaapkamer

- alias: 'Scene - Opstaan aan - Verlichting'
  trigger:
    - platform: state
      entity_id: input_boolean.scene_goodmorning
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.status_donker
      state: 'on'
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: "Woonkamer"
        scene_name: "Opstaan"
    - service: hue.hue_activate_scene
      data:
        group_name: "Keuken"
        scene_name: "Sfeerverlichting"
    - service: hue.hue_activate_scene
      data:
        group_name: "Kantoor"
        scene_name: "Sfeerverlichting"
    - service: homeassistant.turn_on
      entity_id:
        - switch.veranda_lampjes
        - switch.kerstverlichting_dakgoot
        - switch.achtertuin_lampjes
        
- alias: 'Scene - Sfeer aan'
  trigger:
    - platform: state
      entity_id: input_boolean.scene_sfeer
      to: 'on'
  action:
    - service: homeassistant.turn_off
      entity_id:
        - input_boolean.scene_helder
        - switch.ganglicht
        - light.badkamer_spots
    - service: hue.hue_activate_scene
      data:
        group_name: "Woonkamer"
        scene_name: "Sfeerverlichting"
    - service: hue.hue_activate_scene
      data:
        group_name: "Keuken"
        scene_name: "Sfeerverlichting"
    - service: hue.hue_activate_scene
      data:
        group_name: "Kantoor"
        scene_name: "Sfeerverlichting"

- alias: 'Scene - Helder aan'
  trigger:
    - platform: state
      entity_id: input_boolean.scene_helder
      to: 'on'
  action:
    - service: homeassistant.turn_off
      entity_id:
        - input_boolean.scene_sfeer
        - input_boolean.scene_goodmorning
    - service: hue.hue_activate_scene
      data:
        group_name: "Woonkamer"
        scene_name: "Helder"
    - service: hue.hue_activate_scene
      data:
        group_name: "Keuken"
        scene_name: "Helder"

- alias: 'Scene - Badtijd Aan'
  trigger:
    - platform: state
      entity_id: input_boolean.scene_badtijd
      to: 'on'
  # condition:
  #   - condition: state
  #     entity_id: input_boolean.status_donker
  #     state: 'on'
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: "Badkamer"
        scene_name: "Ontspannen"
    - service: climate.set_temperature
      data:
        entity_id: climate.netatmo_badkamer
        temperature: 18.5

- alias: 'Scene - Aan tafel'
  trigger:
    - platform: state
      entity_id: input_boolean.scene_aantafel
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.status_donker
      state: 'on'
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: "Keuken"
        scene_name: "Aan Tafel"
    - service: hue.hue_activate_scene
      data:
        group_name: "Woonkamer"
        scene_name: "Normaal"
    - service: hue.hue_activate_scene
      data:
        group_name: "Kantoor"
        scene_name: "Sfeerverlichting"

- alias: 'Scene - Normaal'
  trigger:
    - platform: state
      entity_id: input_boolean.scene_normaal
      to: 'on'
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: "Woonkamer"
        scene_name: "Normaal"

- alias: 'Scene: Thuiswerken aan'
  trigger:
    - platform: state
      entity_id: input_boolean.scene_thuiswerken
      to: 'on'
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: "Kantoor"
        scene_name: "Normaal"
    - service: switch.turn_on
      entity_id: switch.bureau_martien
    - service: sonos.unjoin
      data_template:
        entity_id:
          - media_player.kantoor
    - service: media_player.volume_set
      data_template:
        volume_level: '0.05'
        entity_id:
          - media_player.kantoor
    - service: media_player.select_source
      data_template:
        entity_id: media_player.kantoor
        source: "KINK"

# - alias: 'Scene: Thuiswerken uit'
#   trigger:
#     - platform: state
#       entity_id: input_boolean.scene_thuiswerken
#       to: 'off'
#   action:
#     - service: homeassistant.turn_off
#       entity_id:
#           - switch.bureau_martien
#           - light.kantoor_bureaulampen
#           - light.kantoor_spots
#     - service: media_player.media_stop
#       data_template:
#         entity_id:
#           - media_player.kantoor