- alias: 'Verlichting: Lichten uit nadat status donker uit is gegaan'
  trigger:
    platform: state
    entity_id: input_boolean.status_donker
    to: 'off'
  condition:
    - condition: state
      entity_id: light.woonkamer_verlichting
      state: 'on'
  action:
    - service: homeassistant.turn_off
      entity_id:
        - light.woonkamer_verlichting
        - light.keuken_verlichting
        - light.overloop_spotjes
        - light.slaapkamer_spotjes

- alias: "Verlichting: Sfeerverlichting in woonkamer bij TV kijken"
  trigger:
    platform: numeric_state
    entity_id: sensor.tv_meubel_power
    above: 70
    for:
      minutes: 5
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: light.hue_play_all
        state: 'on'
      - condition: time
        after: '20:00:00'
        before: '00:00:00'
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: "Woonkamer"
        scene_name: "Sfeerverlichting"

########################################
## Buitenverlichting
########################################
- alias: 'Verlichting: Buitenverlichting aan wanneer donker'
  trigger:
    platform: state
    entity_id: input_boolean.status_donker
    to: 'on'
  action:
    - service: switch.turn_on
      entity_id:
        - switch.veranda_lampjes
        - switch.achtertuin_lampjes

- alias: 'Verlichting: Dakgootlampjes aan bij donker in herfst en winter'
  trigger:
    platform: state
    entity_id: input_boolean.status_donker
    to: 'on'
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: sensor.season
        state: 'autumn'
      - condition: state
        entity_id: sensor.season
        state: 'winter'
  action:
    - service: switch.turn_on
      entity_id: 
        - switch.kerstverlichting_dakgoot

- alias: 'Verlichting: Buitenverlichting uit wanneer licht'
  trigger:
    platform: state
    entity_id: input_boolean.status_donker
    to: 'off'
  action:
    - service: switch.turn_off
      entity_id:
        - switch.kerstverlichting_dakgoot
        - switch.veranda_lampjes
        - switch.achtertuin_lampjes

########################################
## Verlichting bij Donker
########################################
- alias: 'Verlichting: Woonkamerverlichting aan wanneer donker en iemand thuis'
  trigger:
    platform: state
    entity_id: input_boolean.status_donker
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.homemode_home
        state: 'on'
      - condition: state
        entity_id: light.woonkamer_verlichting
        state: 'off'
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: "Woonkamer"
        scene_name: "Normaal"

- alias: 'Verlichting: Keukenverlichting aan wanneer donker en iemand thuis'
  trigger:
    platform: state
    entity_id: input_boolean.status_donker
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.homemode_home
        state: 'on'
      - condition: state
        entity_id: light.keuken_verlichting
        state: 'off'
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: "Keuken"
        scene_name: "Normaal"

- alias: 'Verlichting: Kantoorverlichting aan wanneer donker en iemand thuis'
  trigger:
    platform: state
    entity_id: input_boolean.status_donker
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.homemode_home
        state: 'on'
      - condition: state
        entity_id: light.alle_kantoor_verlichting
        state: 'off'
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: "Kantoor"
        scene_name: "Sfeerverlichting"

- alias: 'Verlichting: CV-ruimte verlichting aan bij deur open'
  trigger:
    platform: state
    entity_id: binary_sensor.cv_ruimte_deur
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.homemode_home
        state: 'on'
      - condition: state
        entity_id: light.cv_ruimte
        state: 'off'
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: "CV-Ruimte"
        scene_name: "Helder"

- alias: 'Verlichting: CV-ruimte verlichting uit bij deur dicht'
  trigger:
    platform: state
    entity_id: binary_sensor.cv_ruimte_deur
    to: 'off'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.homemode_home
        state: 'on'
      - condition: state
        entity_id: light.cv_ruimte
        state: 'on'
  action:
    - service: homeassistant.turn_off
      entity_id: light.cv_ruimte


- alias: 'Verlichting: Washok verlichting aan bij deur open'
  trigger:
    platform: state
    entity_id: binary_sensor.washok_deur
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.homemode_home
        state: 'on'
      - condition: state
        entity_id: light.washok_spots
        state: 'off'
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: "Washok"
        scene_name: "Energie"

- alias: 'Verlichting: Washok verlichting uit bij deur dicht'
  trigger:
    platform: state
    entity_id: binary_sensor.washok_deur
    to: 'off'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.homemode_home
        state: 'on'
      - condition: state
        entity_id: light.washok_spots
        state: 'on'
  action:
    - service: homeassistant.turn_off
      entity_id: light.washok_spots

- alias: 'Verlichting: Licht aan wanneer donker en niemand thuis'
  trigger:
    platform: state
    entity_id: input_boolean.status_donker
    to: 'on'
    for:
      minutes: 30
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.homemode_away
        state: 'on'
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: "Woonkamer"
        scene_name: "Sfeerverlichting"
    - service: hue.hue_activate_scene
      data:
        group_name: "Keuken"
        scene_name: "Sfeerverlichting"
    - service: hue.hue_activate_scene
      data:
        group_name: "Kantoor"
        scene_name: "Sfeerverlichting"
    - service: homeassistant.turn_on
      entity_id:
#        - switch.kerstverlichting_dakgoot
        - switch.veranda_lampjes
        - switch.achtertuin_lampjes

- alias: 'Verlichting: Licht uit om 23:30 when wanneer er niemand thuis is'
  trigger:
    platform: time
    at: '23:30:00'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.homemode_away
        state: 'on'
      - condition: state
        entity_id: input_boolean.homemode_guest
        state: 'off'
  action:
    - service: homeassistant.turn_off
      entity_id:
        - light.alle_verlichting
        - switch.kelderlicht
        - switch.ganglicht
#        - switch.kerstverlichting_dakgoot
        - switch.veranda_lampjes
        - switch.achtertuin_lampjes

########################################
## Verlichting bij beweging
########################################

- alias: 'Verlichting: Ganglight aan bij Beweging'
  trigger:
    - platform: state
      entity_id: binary_sensor.gang_motion
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.homemode_home
        state: 'on'
      - condition: state
        entity_id: input_boolean.status_donker
        state: 'on'
  action:
    - service: switch.turn_on
      entity_id: switch.ganglicht

- alias: 'Verlichting: Ganglight uit bij geen beweging'
  trigger:
    - platform: state
      entity_id: binary_sensor.gang_motion
      to: 'off'
      for:
        minutes: 10
  action:
    - service: switch.turn_off
      entity_id:
        - switch.ganglicht

- alias: 'Verlichting: Keukenlicht naar normaal bij beweging'
  trigger:
    - platform: state
      entity_id: binary_sensor.keuken_motion
      to: 'on'
    - platform: state
      entity_id: binary_sensor.keukendeur
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.homemode_home
        state: 'on'
      - condition: state
        entity_id: input_boolean.status_donker
        state: 'on'
      - condition: state
        entity_id: binary_sensor.nacht
        state: 'off'
      - condition: state
        entity_id: light.keuken_5
        state: 'on'
      - condition: state
        entity_id: light.keuken_4
        state: 'on'
      - condition: state
        entity_id: light.keuken_3
        state: 'off'
      - condition: state
        entity_id: light.keuken_2
        state: 'off'
      - condition: state
        entity_id: light.keuken_1
        state: 'off'
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: "Keuken"
        scene_name: "Normaal"

- alias: 'Verlichting: Keukenlicht naar sfeer bij geen beweging'
  trigger:
    - platform: state
      entity_id: binary_sensor.keuken_motion
      to: 'off'
      for:
        minutes: 15
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.homemode_home
        state: 'on'
      - condition: state
        entity_id: input_boolean.status_donker
        state: 'on'
      - condition: time
        after: '20:00:00'
        before: '00:00:00'
      - condition: state
        entity_id: light.keuken_5
        state: 'on'
      - condition: state
        entity_id: light.keuken_4
        state: 'on'
      - condition: state
        entity_id: light.keuken_3
        state: 'on'
      - condition: state
        entity_id: light.keuken_2
        state: 'on'
      - condition: state
        entity_id: light.keuken_1
        state: 'on'
      - condition: state
        entity_id: light.eetkamertafel
        state: 'off'
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: "Keuken"
        scene_name: "Sfeerverlichting"